import path from 'node:path'
import type { Capability, ControllerConfig, DeployRequest, DeployResult, Inventory, Parameter, ServiceAction, ServiceDefinition } from '@dsh-docker-services/shared'
import { assertDeployRequest, redact } from '@dsh-docker-services/shared'
import type { DockerAdapter } from './docker.js'
import { assertTrustedExecutable, runBounded } from './docker.js'
import { AuditLog, capabilityFor, KeyedFileCheckpointSink, LeaseLockManager, readDeployment, saveDeployment, SecretStore } from './state.js'
import { durableAtomicWrite, ensureOwnedRoot, minimalEnv, SafeError } from './security.js'

export type Identity = {actor: string; role: string; capabilities: readonly Capability[]}
export class Controller {
  private constructor(readonly config: ControllerConfig, private readonly docker: DockerAdapter, private readonly audit: AuditLog, private readonly locks: LeaseLockManager, private readonly secrets: SecretStore) {}
  static async create(config: ControllerConfig, docker: DockerAdapter): Promise<Controller> { await ensureOwnedRoot(config.stateDir); await ensureOwnedRoot(config.secretRoot); const checkpoint = await KeyedFileCheckpointSink.create(config.audit.checkpointFile, config.audit.checkpointKeyFile); const audit = await AuditLog.create(config.stateDir, checkpoint); return new Controller(config, docker, audit, new LeaseLockManager(config.stateDir), new SecretStore(config.secretRoot)) }
  private service(name: string): ServiceDefinition { const service = this.config.services.find(candidate => candidate.name === name); if (!service) throw new SafeError('not_found', 404, 'service is not allowlisted'); return service }
  private async authorize(identity: Identity, capability: Capability, action: string, service?: string, secret?: string): Promise<void> { if (!identity.actor || !identity.capabilities.includes(capability)) { await this.audit.append({actor: identity.actor || 'anonymous', capability, action, service, secret, outcome: 'denied'}); throw new SafeError('forbidden', 403, 'capability denied') } }
  private event(identity: Identity, capability: Capability, action: string, outcome: 'ok' | 'error', service?: string, secret?: string, details?: Record<string, string>): Promise<void> { return this.audit.append({actor: identity.actor, capability, action, service, secret, outcome, details}) }
  async inventory(identity: Identity, signal?: AbortSignal): Promise<Inventory> { await this.authorize(identity, 'services:read', 'inventory'); const all = await this.docker.inventory(signal); const known = new Set(this.config.services.flatMap(service => service.containers)); const services = await Promise.all(this.config.services.map(async service => { const containers = all.filter(container => service.containers.includes(container.name)).map(container => ({...container, controlled: true})); const deployment = await readDeployment(this.config.stateDir, service.name); const healthy = containers.length > 0 && containers.every(container => container.health === 'healthy' || (container.health === null && container.status === 'running')); return {name: service.name, displayName: service.displayName ?? service.name, actions: service.actions, containers, parameters: service.parameters ?? [], deployment: deployment ? {repo: deployment.repo, branch: deployment.branch, sha: deployment.sha, imageDigest: deployment.imageDigest, deployedAt: deployment.deployedAt, testState: deployment.testState, url: service.url ?? null} : null, health: containers.length ? (healthy ? 'healthy' : 'degraded') : 'unknown'} as const })); await this.event(identity, 'services:read', 'inventory', 'ok'); return {protocolVersion: 1, instance: this.config.instance, generatedAt: new Date().toISOString(), services, unmanaged: all.filter(container => !known.has(container.name))} }
  async logs(identity: Identity, serviceName: string, tail = 200, signal?: AbortSignal): Promise<{logs: string}> { const service = this.service(serviceName); this.requireAction(service, 'logs'); await this.authorize(identity, 'services:read', 'logs', service.name); const count = Number.isFinite(tail) ? Math.max(1, Math.min(1000, Math.trunc(tail))) : 200; const logs = redact(await this.docker.logs(service, count, signal)); await this.event(identity, 'services:read', 'logs', 'ok', service.name); return {logs} }
  async action(identity: Identity, serviceName: string, action: 'start' | 'stop' | 'restart', signal?: AbortSignal): Promise<{ok: true}> { const service = this.service(serviceName); this.requireAction(service, action); const capability = capabilityFor(action); await this.authorize(identity, capability, action, service.name); try { await this.docker.action(service, action, signal); await this.event(identity, capability, action, 'ok', service.name); return {ok: true} } catch (error) { await this.event(identity, capability, action, 'error', service.name); throw error } }
  async deploy(identity: Identity, serviceName: string, input: unknown, signal?: AbortSignal): Promise<DeployResult> {
    const service = this.service(serviceName); this.requireAction(service, 'deploy'); await this.authorize(identity, 'deploy:execute', 'deploy', service.name); try { assertDeployRequest(input) } catch { throw new SafeError('bad_request', 400, 'invalid deploy request') }; const request = input as DeployRequest; const policy = service.deploy
    if (!policy || !policy.repositories.includes(request.repo) || !policy.branches.includes(request.branch)) throw new SafeError('forbidden', 403, 'deployment does not match policy')
    const completed = await readDeployment(this.config.stateDir, service.name); if (completed?.idempotencyKey === request.idempotencyKey) { if (completed.repo !== request.repo || completed.branch !== request.branch || completed.sha.toLowerCase() !== request.sha.toLowerCase()) throw new SafeError('conflict', 409, 'idempotency key reused for another revision'); const {idempotencyKey: _key, ...result} = completed; return result }
    return this.locks.withLease(service.name, request.idempotencyKey, policy.leaseMs ?? 5 * 60_000, async () => { try { const result = await this.docker.deploy(service, request, signal); await saveDeployment(this.config.stateDir, service.name, request.idempotencyKey, result); await this.event(identity, 'deploy:execute', 'deploy', 'ok', service.name, undefined, {repo: result.repo, branch: result.branch, sha: result.sha, imageDigest: result.imageDigest, testState: result.testState}); return result } catch (error) { await this.event(identity, 'deploy:execute', 'deploy', 'error', service.name); throw error } })
  }
  async parameters(identity: Identity, serviceName: string, values: unknown): Promise<{saved: string[]}> { const service = this.service(serviceName); this.requireAction(service, 'parameters:write'); await this.authorize(identity, 'parameters:write', 'parameters', service.name); if (!values || typeof values !== 'object' || Array.isArray(values)) throw new SafeError('bad_request', 400, 'parameter values must be an object'); const accepted: Record<string, string> = {}; const schema = new Map((service.parameters ?? []).map(parameter => [parameter.key, parameter])); for (const [key, value] of Object.entries(values as Record<string, unknown>)) { const parameter = schema.get(key); if (!parameter) throw new SafeError('bad_request', 400, `parameter is not allowlisted: ${key}`); accepted[key] = validateParameter(parameter, value) } const directory = path.join(this.config.stateDir, 'parameters'); await ensureOwnedRoot(directory); await durableAtomicWrite(path.join(directory, `${service.name}.json`), JSON.stringify(accepted)); await this.event(identity, 'parameters:write', 'parameters', 'ok', service.name, undefined, {keys: Object.keys(accepted).sort().join(',')}); return {saved: Object.keys(accepted).sort()} }
  async secret(identity: Identity, serviceName: string, secretId: string, operation: 'status' | 'set' | 'rotate' | 'test', value?: unknown, signal?: AbortSignal): Promise<{configured: boolean; updatedAt: string | null}> { const service = this.service(serviceName); const secret = service.secrets?.find(candidate => candidate.id === secretId); if (!secret) throw new SafeError('not_found', 404, 'secret is not allowlisted'); const action = `secret:${operation}` as ServiceAction; this.requireAction(service, action); const capability = capabilityFor(action); await this.authorize(identity, capability, action, service.name, secret.id); if (operation === 'status') { const result = await this.secrets.status(secret); await this.event(identity, capability, action, 'ok', service.name, secret.id); return result } if (operation === 'test') { if (!secret.testHook) throw new SafeError('not_found', 404, 'secret test is not configured'); await assertTrustedExecutable(secret.testHook); await runBounded(secret.testHook, ['--service', service.name, '--secret-id', secret.id], {signal, operation: 'secret-test-hook', timeoutMs: 60_000, maxOutputBytes: 16 * 1024, env: minimalEnv()}); const result = await this.secrets.status(secret); await this.event(identity, capability, action, 'ok', service.name, secret.id); return result } try { await this.secrets.set(secret, value) } catch { throw new SafeError('bad_request', 400, 'secret rejected by schema or target policy') }; const result = await this.secrets.status(secret); await this.event(identity, capability, action, 'ok', service.name, secret.id); return result }
  async health(identity: Identity): Promise<{ok: boolean; instance: string; audit: ReturnType<AuditLog['health']>}> { await this.authorize(identity, 'services:read', 'health'); const audit = this.audit.health(); return {ok: audit.healthy, instance: this.config.instance, audit} }
  async auditEntries(identity: Identity, limit = 100): Promise<unknown[]> { await this.authorize(identity, 'audit:read', 'audit'); return this.audit.read(Number.isFinite(limit) ? limit : 100) }
  private requireAction(service: ServiceDefinition, action: ServiceAction): void { if (!service.actions.includes(action)) throw new SafeError('forbidden', 403, 'service action is not allowlisted') }
}
function validateParameter(parameter: Parameter, value: unknown): string { if (!['string', 'number', 'boolean'].includes(typeof value)) throw new SafeError('bad_request', 400, 'parameter must be scalar'); const result = String(value); if (result.length > 4096 || /[\0\r\n]/.test(result)) throw new SafeError('bad_request', 400, 'parameter exceeds bounds'); if (parameter.type === 'integer' && !/^-?\d+$/.test(result)) throw new SafeError('bad_request', 400, 'parameter must be integer'); if (parameter.type === 'boolean' && !['true', 'false'].includes(result)) throw new SafeError('bad_request', 400, 'parameter must be boolean'); if (parameter.type === 'enum' && !parameter.enum?.includes(result)) throw new SafeError('bad_request', 400, 'parameter enum rejected'); if (parameter.pattern && !(new RegExp(parameter.pattern, 'u').test(result))) throw new SafeError('bad_request', 400, 'parameter pattern rejected'); return result }
