import { mkdir, readFile, writeFile } from 'node:fs/promises'
import path from 'node:path'
import type { Capability, ContainerView, ControllerConfig, DeployRequest, Inventory, Parameter, ServiceAction, ServiceDefinition } from '@dsh-docker-services/shared'
import { assertDeployRequest } from '@dsh-docker-services/shared'
import type { DockerAdapter } from './docker.js'
import { AuditLog, capabilityFor, LockManager, readDeployment, saveDeployment, SecretStore } from './state.js'

export type Identity = { actor: string; capabilities: readonly Capability[] }
export class ControllerError extends Error { constructor(message: string, readonly status = 400) { super(message) } }
export class Controller {
  private readonly audit: AuditLog; private readonly locks: LockManager; private readonly secrets: SecretStore
  constructor(readonly config: ControllerConfig, private readonly docker: DockerAdapter) { this.audit = new AuditLog(config.stateDir); this.locks = new LockManager(config.stateDir); this.secrets = new SecretStore(config.secretRoot) }
  private service(name: string): ServiceDefinition { const service = this.config.services.find(candidate => candidate.name === name); if (!service) throw new ControllerError('service is not allowlisted', 404); return service }
  private async authorize(identity: Identity, capability: Capability, action: string, service?: string, secret?: string): Promise<void> { if (!identity.actor || !identity.capabilities.includes(capability)) { await this.audit.append({actor: identity.actor || 'anonymous', capability, action, service, secret, outcome: 'denied'}); throw new ControllerError('capability denied', 403) } }
  private async event(identity: Identity, capability: Capability, action: string, outcome: 'ok' | 'error', service?: string, secret?: string, details?: Record<string, string>): Promise<void> { await this.audit.append({actor: identity.actor, capability, action, service, secret, outcome, details}) }
  async inventory(identity: Identity): Promise<Inventory> {
    await this.authorize(identity, 'services:read', 'inventory'); const all = await this.docker.inventory(); const known = new Set(this.config.services.flatMap(service => service.containers)); const services = await Promise.all(this.config.services.map(async service => {
      const containers = all.filter(container => service.containers.includes(container.name)).map(container => ({...container, controlled: true})); const deployment = await readDeployment(this.config.stateDir, service.name)
      const healthy = containers.length && containers.every(container => container.health === 'healthy' || (container.health === null && container.status === 'running'))
      return {name: service.name, displayName: service.displayName ?? service.name, actions: service.actions, containers, parameters: service.parameters ?? [], deployment: {repo: deployment?.repo ?? null, branch: deployment?.branch ?? null, sha: deployment?.sha ?? null, imageDigest: deployment?.imageDigest ?? containers[0]?.imageDigest ?? null, deployedAt: deployment?.deployedAt ?? null, testState: deployment?.testState ?? 'unknown', url: service.url ?? null}, health: containers.length ? (healthy ? 'healthy' : 'degraded') : 'unknown'} as const
    }))
    await this.event(identity, 'services:read', 'inventory', 'ok'); return {protocolVersion: 1, instance: this.config.instance, generatedAt: new Date().toISOString(), services, unmanaged: all.filter(container => !known.has(container.name))}
  }
  async logs(identity: Identity, serviceName: string, tail = 200): Promise<{logs: string}> { const service = this.service(serviceName); this.requireAction(service, 'logs'); await this.authorize(identity, 'services:read', 'logs', service.name); const logs = await this.docker.logs(service, Math.max(1, Math.min(1000, Math.trunc(tail)))); await this.event(identity, 'services:read', 'logs', 'ok', service.name); return {logs} }
  async action(identity: Identity, serviceName: string, action: 'start' | 'stop' | 'restart'): Promise<{ok: true}> { const service = this.service(serviceName); this.requireAction(service, action); const cap = capabilityFor(action); await this.authorize(identity, cap, action, service.name); try { await this.docker.action(service, action); await this.event(identity, cap, action, 'ok', service.name); return {ok: true} } catch (error) { await this.event(identity, cap, action, 'error', service.name); throw error } }
  async deploy(identity: Identity, serviceName: string, input: unknown): Promise<{ok: true}> { const service = this.service(serviceName); this.requireAction(service, 'deploy'); await this.authorize(identity, 'deploy:execute', 'deploy', service.name); assertDeployRequest(input); const request = input as DeployRequest; const policy = service.deploy; if (!policy || !policy.repositories.includes(request.repo) || !policy.branches.includes(request.branch) || (policy.requireImageDigest && !request.imageDigest)) throw new ControllerError('deployment does not match the service exact-revision policy', 403)
    return this.locks.withLock(service.name, async () => { try { await this.docker.deploy(service, request); await saveDeployment(this.config.stateDir, service.name, request); await this.event(identity, 'deploy:execute', 'deploy', 'ok', service.name, undefined, {repo: request.repo, branch: request.branch, sha: request.sha, imageDigest: request.imageDigest ?? ''}); return {ok: true} } catch (error) { await this.event(identity, 'deploy:execute', 'deploy', 'error', service.name); throw error } })
  }
  async parameters(identity: Identity, serviceName: string, values: unknown): Promise<{saved: string[]}> { const service = this.service(serviceName); this.requireAction(service, 'parameters:write'); await this.authorize(identity, 'parameters:write', 'parameters', service.name); if (!values || typeof values !== 'object' || Array.isArray(values)) throw new ControllerError('parameter values must be an object'); const accepted: Record<string, string> = {}; const schema = new Map((service.parameters ?? []).map(parameter => [parameter.key, parameter])); for (const [key, value] of Object.entries(values as Record<string, unknown>)) { const parameter = schema.get(key); if (!parameter) throw new ControllerError(`parameter is not allowlisted: ${key}`); accepted[key] = validateParameter(parameter, value) }
    const directory = path.join(this.config.stateDir, 'parameters'); await mkdir(directory, {recursive: true, mode: 0o700}); await writeFile(path.join(directory, `${service.name}.json`), JSON.stringify(accepted), {mode: 0o600}); await this.event(identity, 'parameters:write', 'parameters', 'ok', service.name, undefined, {keys: Object.keys(accepted).sort().join(',')}); return {saved: Object.keys(accepted).sort()}
  }
  async secret(identity: Identity, serviceName: string, secretId: string, operation: 'status' | 'set' | 'rotate' | 'test', value?: unknown): Promise<{configured: boolean; updatedAt: string | null}> { const service = this.service(serviceName); const secret = service.secrets?.find(candidate => candidate.id === secretId); if (!secret) throw new ControllerError('secret is not allowlisted', 404); const action = `secret:${operation}` as ServiceAction; this.requireAction(service, action); const cap = capabilityFor(action); await this.authorize(identity, cap, action, service.name, secret.id); if (operation === 'status') { const result = await this.secrets.status(secret); await this.event(identity, cap, action, 'ok', service.name, secret.id); return result } if (operation === 'test') { if (!secret.testHook) throw new ControllerError('secret test is not configured', 404); const {fixedCommand} = await import('./docker.js'); await fixedCommand(secret.testHook, ['--service', service.name, '--secret-id', secret.id]); const result = await this.secrets.status(secret); await this.event(identity, cap, action, 'ok', service.name, secret.id); return result } await this.secrets.set(secret, value); const result = await this.secrets.status(secret); await this.event(identity, cap, action, 'ok', service.name, secret.id); return result }
  async health(identity: Identity): Promise<{ok: true; instance: string}> { await this.authorize(identity, 'services:read', 'health'); return {ok: true, instance: this.config.instance} }
  async auditEntries(identity: Identity, limit = 100): Promise<unknown[]> { await this.authorize(identity, 'audit:read', 'audit'); return this.audit.read(limit) }
  private requireAction(service: ServiceDefinition, action: ServiceAction): void { if (!service.actions.includes(action)) throw new ControllerError('service action is not allowlisted', 403) }
}
function validateParameter(parameter: Parameter, value: unknown): string { const result = String(value); if (parameter.type === 'integer' && !/^-?\d+$/.test(result)) throw new ControllerError(`${parameter.key} must be an integer`); if (parameter.type === 'boolean' && !['true', 'false'].includes(result)) throw new ControllerError(`${parameter.key} must be true or false`); if (parameter.type === 'enum' && !parameter.enum?.includes(result)) throw new ControllerError(`${parameter.key} is not an allowed value`); if (parameter.pattern && !(new RegExp(parameter.pattern).test(result))) throw new ControllerError(`${parameter.key} does not match its pattern`); return result }
export async function loadParameters(root: string, service: string): Promise<Record<string, string>> { try { return JSON.parse(await readFile(path.join(root, 'parameters', `${service}.json`), 'utf8')) } catch { return {} } }
