import { spawn } from 'node:child_process'
import { lstat } from 'node:fs/promises'
import https from 'node:https'
import type { ContainerView, ControllerConfig, DeployRequest, DeployResult, DockerConfig, ServiceDefinition } from '@dsh-docker-services/shared'
import { assertDeployResult, patterns, redact } from '@dsh-docker-services/shared'
import { assertNoSymlinkComponents, minimalEnv, readProtectedFile, SafeError } from './security.js'

type RunOptions = { timeoutMs?: number; maxOutputBytes?: number; maxErrorBytes?: number; signal?: AbortSignal; input?: string; env?: NodeJS.ProcessEnv }
export class CommandExecutionError extends Error {
  readonly protectedDetails!: string
  constructor(readonly commandCode: 'spawn_failed' | 'stdin_failed' | 'exit_nonzero', details: string) { super(`trusted executable failed: ${commandCode}`); this.name = 'CommandExecutionError'; Object.defineProperty(this, 'protectedDetails', {value: redact(details), enumerable: false, writable: false}) }
}
export async function runBounded(file: string, args: string[], options: RunOptions = {}): Promise<{stdout: string; stderr: string}> {
  if (!patterns.absolute.test(file)) throw new Error('executable must be an absolute path')
  const timeoutMs = Math.max(100, Math.min(60 * 60_000, options.timeoutMs ?? 30_000)); const maxOutput = Math.max(1024, Math.min(8 * 1024 * 1024, options.maxOutputBytes ?? 1024 * 1024)); const maxError = Math.max(1024, Math.min(64 * 1024, options.maxErrorBytes ?? 16 * 1024))
  return new Promise((resolve, reject) => {
    let settled = false; let outputBytes = 0; let errorBytes = 0; let timer: NodeJS.Timeout | undefined; const stdout: Buffer[] = []; const stderr: Buffer[] = []
    const child = spawn(file, args, {stdio: ['pipe', 'pipe', 'pipe'], windowsHide: true, env: options.env ?? minimalEnv()})
    const finish = (error?: Error) => { if (settled) return; settled = true; if (timer) clearTimeout(timer); options.signal?.removeEventListener('abort', abort); if (error) reject(error); else resolve({stdout: Buffer.concat(stdout).toString('utf8'), stderr: Buffer.concat(stderr).toString('utf8')}) }
    const abort = () => { child.kill('SIGKILL'); finish(new SafeError('unavailable', 503, 'operation cancelled')) }; options.signal?.addEventListener('abort', abort, {once: true})
    timer = setTimeout(() => { child.kill('SIGKILL'); finish(new SafeError('unavailable', 503, 'operation timed out')) }, timeoutMs); timer.unref(); if (options.signal?.aborted) abort()
    child.stdout.on('data', chunk => { outputBytes += chunk.length; if (outputBytes > maxOutput) { child.kill('SIGKILL'); finish(new SafeError('unavailable', 503, 'operation output exceeded bound')) } else stdout.push(Buffer.from(chunk)) })
    child.stderr.on('data', chunk => { errorBytes += chunk.length; if (errorBytes <= maxError) stderr.push(Buffer.from(chunk)) })
    child.on('error', error => finish(new CommandExecutionError('spawn_failed', `code=${(error as NodeJS.ErrnoException).code ?? 'unknown'}`))); child.on('close', code => { if (code !== 0) finish(new CommandExecutionError('exit_nonzero', `exit=${String(code)} stderr=${Buffer.concat(stderr).toString('utf8')}`)); else finish() })
    child.stdin.on('error', error => { const code = (error as NodeJS.ErrnoException).code; if (code === 'EPIPE' || code === 'ERR_STREAM_DESTROYED') return; child.kill('SIGKILL'); finish(new CommandExecutionError('stdin_failed', `code=${code ?? 'unknown'}`)) })
    if (options.input !== undefined) { if (Buffer.byteLength(options.input) > 64 * 1024) return abort(); child.stdin.end(options.input) } else child.stdin.end()
  })
}
export async function assertTrustedExecutable(file: string): Promise<void> { await assertNoSymlinkComponents(file); const info = await lstat(file); if (!info.isFile() || info.isSymbolicLink() || info.uid !== 0 || (info.mode & 0o022) !== 0) throw new Error(`untrusted executable rejected: ${file}`) }
export async function assertDockerSocket(host: string): Promise<void> { const socket = host.slice('unix://'.length); await assertNoSymlinkComponents(socket); const info = await lstat(socket); if (!info.isSocket() || info.isSymbolicLink()) throw new Error('configured Docker endpoint is not a Unix socket') }
export interface DockerAdapter { inventory(signal?: AbortSignal): Promise<ContainerView[]>; action(service: ServiceDefinition, action: 'start' | 'stop' | 'restart', signal?: AbortSignal): Promise<void>; logs(service: ServiceDefinition, tail: number, signal?: AbortSignal): Promise<string>; deploy(service: ServiceDefinition, request: DeployRequest, signal?: AbortSignal): Promise<DeployResult> }
function digestOf(raw: any): string | null { const configured = raw.Config?.Image; if (typeof configured === 'string' && configured.includes('@sha256:')) return configured.slice(configured.indexOf('@') + 1); const value = raw.RepoDigests?.find((entry: unknown) => typeof entry === 'string' && entry.includes('@sha256:')); return typeof value === 'string' ? value.slice(value.indexOf('@') + 1) : null }
function normalize(raw: any, stats?: {CPUPerc?: string; MemUsage?: string}): ContainerView { const state = raw.State ?? {}; const config = raw.Config ?? {}; return {name: String(raw.Name ?? '').replace(/^\//, ''), image: String(config.Image ?? raw.Image ?? ''), imageDigest: digestOf(raw), status: String(state.Status ?? 'unknown'), health: typeof state.Health?.Status === 'string' ? state.Health.Status : null, startedAt: typeof state.StartedAt === 'string' ? state.StartedAt : null, resources: {cpuPercent: stats?.CPUPerc ? Number.parseFloat(stats.CPUPerc) : null, memoryBytes: stats?.MemUsage ? parseBytes(stats.MemUsage.split('/')[0]!.trim()) : null}, controlled: false} }
function parseBytes(value: string): number | null { const match = value.match(/^([0-9.]+)([KMGTP]?i?B)$/i); if (!match) return null; const powers: Record<string, number> = {B: 0, KB: 1, KIB: 1, MB: 2, MIB: 2, GB: 3, GIB: 3, TB: 4, TIB: 4}; return Math.round(Number(match[1]) * 1024 ** (powers[match[2]!.toUpperCase()] ?? 0)) }
function verifyDeployedContainers(service: ServiceDefinition, containers: ContainerView[], digest: string): void {
  const actual = containers.filter(container => service.containers.includes(container.name))
  const names = new Set(actual.map(container => container.name))
  if (actual.length !== service.containers.length || service.containers.some(name => !names.has(name)) || actual.some(container => container.imageDigest !== digest)) throw new Error('deployed containers failed exact digest verification')
  const policy = service.deploy?.runtimePolicy ?? {requireRunning: true, requireHealthy: true}
  if (policy.requireRunning && actual.some(container => container.status !== 'running')) throw new Error('deployed containers failed running-state verification')
  if (policy.requireHealthy && actual.some(container => container.health !== 'healthy')) throw new Error('deployed containers failed health verification')
}
export class LocalDockerAdapter implements DockerAdapter {
  constructor(private readonly config: DockerConfig) {}
  private run(args: string[], options: RunOptions = {}) { return runBounded(this.config.binary, ['--host', this.config.host, ...args], {...options, env: minimalEnv({DOCKER_HOST: this.config.host})}) }
  async inventory(signal?: AbortSignal): Promise<ContainerView[]> { const ids = (await this.run(['ps', '--all', '--quiet'], {signal, maxOutputBytes: 1024 * 1024})).stdout.trim().split(/\s+/).filter(Boolean); if (ids.length > 2048) throw new Error('Docker inventory exceeds container bound'); if (!ids.length) return []; const raw = JSON.parse((await this.run(['inspect', ...ids], {signal, maxOutputBytes: 8 * 1024 * 1024})).stdout); const byName = new Map<string, any>(); try { const stats = (await this.run(['stats', '--no-stream', '--format', '{{json .}}', ...ids], {signal, maxOutputBytes: 2 * 1024 * 1024})).stdout; for (const line of stats.split('\n').filter(Boolean)) { const value = JSON.parse(line); byName.set(String(value.Name), value) } } catch {} return raw.map((item: any) => normalize(item, byName.get(String(item.Name ?? '').replace(/^\//, '')))) }
  async action(service: ServiceDefinition, action: 'start' | 'stop' | 'restart', signal?: AbortSignal): Promise<void> { await this.run([action, ...service.containers], {signal}) }
  async logs(service: ServiceDefinition, tail: number, signal?: AbortSignal): Promise<string> { return (await this.run(['logs', '--tail', String(tail), service.containers[0]!], {signal, maxOutputBytes: 1024 * 1024})).stdout }
  async deploy(service: ServiceDefinition, request: DeployRequest, signal?: AbortSignal): Promise<DeployResult> { if (!service.deploy) throw new Error('deployment is not configured'); await assertTrustedExecutable(service.deploy.hook); const output = await runBounded(service.deploy.hook, ['--service', service.name, '--repo', request.repo, '--branch', request.branch, '--sha', request.sha], {signal, timeoutMs: service.deploy.timeoutMs ?? 30 * 60_000, maxOutputBytes: 64 * 1024, env: minimalEnv({DOCKER_HOST: this.config.host})}); let result: unknown; try { result = JSON.parse(output.stdout) } catch { throw new Error('deploy hook returned invalid JSON') } assertDeployResult(result, request); verifyDeployedContainers(service, await this.inventory(signal), result.imageDigest); return result }
}
export type RemoteCall = {operation: 'inventory'} | {operation: 'action'; service: string; action: 'start' | 'stop' | 'restart'} | {operation: 'logs'; service: string; tail: number} | {operation: 'deploy'; service: string; deployment: DeployRequest}
export interface RemoteTransport { call(request: RemoteCall, signal?: AbortSignal): Promise<unknown> }
export class SshJsonTransport implements RemoteTransport {
  constructor(private readonly config: NonNullable<DockerConfig['ssh']>) {}
  async call(request: RemoteCall, signal?: AbortSignal): Promise<unknown> { if (!/^[a-zA-Z0-9.-]+$/.test(this.config.host) || !/^[a-z_][a-z0-9_-]*$/i.test(this.config.user)) throw new Error('invalid constrained SSH configuration'); const args = ['-o', 'BatchMode=yes', '-o', 'StrictHostKeyChecking=yes', '-o', `UserKnownHostsFile=${this.config.knownHosts}`, '-o', 'ClearAllForwardings=yes', '-o', 'PermitLocalCommand=no', '-p', String(this.config.port ?? 22), '-l', this.config.user, ...(this.config.identityFile ? ['-i', this.config.identityFile] : []), '--', this.config.host, this.config.helper]; const result = await runBounded(this.config.binary, args, {signal, input: JSON.stringify(request), timeoutMs: this.config.timeoutMs ?? 60_000, maxOutputBytes: this.config.maxOutputBytes ?? 1024 * 1024}); let response: any; try { response = JSON.parse(result.stdout) } catch { throw new Error('remote SSH adapter returned invalid JSON') } if (response?.ok !== true) throw new Error('remote SSH adapter rejected request'); return response.value }
}
export class TlsJsonTransport implements RemoteTransport {
  constructor(private readonly config: NonNullable<DockerConfig['tls']>) {}
  async call(request: RemoteCall, signal?: AbortSignal): Promise<unknown> { const url = new URL(this.config.url); if (url.protocol !== 'https:' || url.username || url.password || url.hash) throw new Error('invalid fixed TLS endpoint'); const [ca, cert, key] = await Promise.all([readProtectedFile(this.config.caFile, 1024 * 1024), readProtectedFile(this.config.certFile, 1024 * 1024), readProtectedFile(this.config.keyFile, 1024 * 1024)]); const payload = JSON.stringify(request); const limit = this.config.maxOutputBytes ?? 1024 * 1024; return new Promise((resolve, reject) => { let settled = false; const finish = (error?: Error, value?: unknown) => { if (settled) return; settled = true; clearTimeout(timer); signal?.removeEventListener('abort', abort); error ? reject(error) : resolve(value) }; const req = https.request(url, {method: 'POST', ca, cert, key, servername: this.config.serverName, rejectUnauthorized: true, signal, headers: {'content-type': 'application/json', 'content-length': Buffer.byteLength(payload)}}, res => { const chunks: Buffer[] = []; let bytes = 0; res.on('data', chunk => { bytes += chunk.length; if (bytes > limit) { req.destroy(); finish(new SafeError('unavailable', 503, 'TLS response exceeded bound')) } else chunks.push(Buffer.from(chunk)) }); res.on('end', () => { try { const body = JSON.parse(Buffer.concat(chunks).toString('utf8')); if ((res.statusCode ?? 500) >= 400 || body?.ok !== true) finish(new Error('remote TLS adapter rejected request')); else finish(undefined, body.value) } catch { finish(new Error('remote TLS adapter returned invalid JSON')) } }) }); const abort = () => { req.destroy(); finish(new SafeError('unavailable', 503, 'TLS request cancelled')) }; signal?.addEventListener('abort', abort, {once: true}); const timer = setTimeout(() => { req.destroy(); finish(new SafeError('unavailable', 503, 'TLS request timed out')) }, this.config.timeoutMs ?? 60_000); timer.unref(); if (signal?.aborted) abort(); req.on('error', error => finish(error)); req.end(payload) }) }
}
export class RemoteDockerAdapter implements DockerAdapter {
  constructor(private readonly transport: RemoteTransport) {}
  async inventory(signal?: AbortSignal): Promise<ContainerView[]> { return await this.transport.call({operation: 'inventory'}, signal) as ContainerView[] }
  async action(service: ServiceDefinition, action: 'start' | 'stop' | 'restart', signal?: AbortSignal): Promise<void> { await this.transport.call({operation: 'action', service: service.name, action}, signal) }
  async logs(service: ServiceDefinition, tail: number, signal?: AbortSignal): Promise<string> { const value = await this.transport.call({operation: 'logs', service: service.name, tail}, signal); return String((value as {logs?: string}).logs ?? '') }
  async deploy(service: ServiceDefinition, request: DeployRequest, signal?: AbortSignal): Promise<DeployResult> { const value = await this.transport.call({operation: 'deploy', service: service.name, deployment: request}, signal); assertDeployResult(value, request); verifyDeployedContainers(service, await this.inventory(signal), value.imageDigest); return value }
}
