import http, { type IncomingMessage, type ServerResponse } from 'node:http'
import type { Controller, Identity } from './controller.js'
import { ControllerError } from './controller.js'
import type { Capability, ControllerConfig } from '@dsh-docker-services/shared'

export function identityFromRequest(req: IncomingMessage, config: ControllerConfig): Identity {
  // A reverse proxy or Unix-socket peer must authenticate the actor. This reference maps a trusted injected role, never capabilities from the client.
  const actor = String(req.headers['x-dsh-actor'] ?? ''); const role = String(req.headers['x-dsh-role'] ?? ''); const capabilities = config.roles.find(entry => entry.name === role)?.capabilities ?? []
  return {actor, capabilities}
}
async function body(req: IncomingMessage): Promise<any> { const chunks: Buffer[] = []; let bytes = 0; for await (const chunk of req) { bytes += chunk.length; if (bytes > 64 * 1024) throw new ControllerError('request body too large', 413); chunks.push(Buffer.from(chunk)) } if (!chunks.length) return {}; try { return JSON.parse(Buffer.concat(chunks).toString('utf8')) } catch { throw new ControllerError('invalid JSON body') } }
function send(res: ServerResponse, status: number, value: unknown): void { const payload = JSON.stringify(value); res.writeHead(status, {'content-type': 'application/json', 'content-length': Buffer.byteLength(payload), 'cache-control': 'no-store'}); res.end(payload) }
export function createServer(controller: Controller): http.Server { return http.createServer(async (req, res) => { try { const url = new URL(req.url ?? '/', 'http://localhost'); const identity = identityFromRequest(req, controller.config); if (req.method === 'GET' && url.pathname === '/v1/health') return send(res, 200, await controller.health(identity)); if (req.method === 'GET' && url.pathname === '/v1/services') return send(res, 200, await controller.inventory(identity)); if (req.method === 'GET' && url.pathname === '/v1/audit') return send(res, 200, await controller.auditEntries(identity, Number(url.searchParams.get('limit') ?? '100'))); const service = url.pathname.match(/^\/v1\/services\/([a-z0-9-]+)(?:\/(.+))?$/); if (!service) throw new ControllerError('not found', 404); const name = service[1]!; const action = service[2] ?? ''; if (req.method === 'GET' && action === 'logs') return send(res, 200, await controller.logs(identity, name, Number(url.searchParams.get('tail') ?? '200'))); if (req.method !== 'POST') throw new ControllerError('method not allowed', 405); const payload = await body(req); if (['start', 'stop', 'restart'].includes(action)) return send(res, 200, await controller.action(identity, name, action as 'start' | 'stop' | 'restart')); if (action === 'deploy') return send(res, 200, await controller.deploy(identity, name, payload)); if (action === 'parameters') return send(res, 200, await controller.parameters(identity, name, payload.values)); const secret = action.match(/^secrets\/([a-z0-9-]+)\/(status|set|rotate|test)$/); if (secret) return send(res, 200, await controller.secret(identity, name, secret[1]!, secret[2] as 'status' | 'set' | 'rotate' | 'test', payload.value)); throw new ControllerError('not found', 404) } catch (error) { const known = error instanceof ControllerError; send(res, known ? error.status : 500, {error: error instanceof Error ? error.message : 'internal error'}) } }) }
