import assert from 'node:assert/strict'
import {chmod, mkdtemp, writeFile} from 'node:fs/promises'
import os from 'node:os'
import path from 'node:path'
import test from 'node:test'
import {CommandExecutionError, RemoteDockerAdapter, runBounded, SshJsonTransport, TlsJsonTransport, type RemoteCall, type RemoteTransport} from '../src/docker.js'
import type {DeployResult, ServiceDefinition} from '@dsh-docker-services/shared'

test('bounded process execution rejects output floods, timeout, and cancellation', async () => {
  await assert.rejects(() => runBounded(process.execPath, ['-e', 'process.stdout.write("x".repeat(10000))'], {maxOutputBytes: 1024}), /exceeded bound/)
  await assert.rejects(() => runBounded(process.execPath, ['-e', 'setInterval(()=>{},1000)'], {timeoutMs: 100}), /timed out/)
  const abort = new AbortController(); const pending = runBounded(process.execPath, ['-e', 'setInterval(()=>{},1000)'], {timeoutMs: 10_000, signal: abort.signal}); abort.abort(); await assert.rejects(() => pending, /cancelled/)
  const preAborted = new AbortController(); preAborted.abort(); await assert.rejects(() => runBounded(process.execPath, ['-e', 'setInterval(()=>{},1000)'], {signal: preAborted.signal}), /cancelled/)
})
test('runBounded absorbs closed-stdin EPIPE on Node 24-compatible streams', async () => { const result = await runBounded(process.execPath, ['-e', 'process.stdin.destroy();setTimeout(()=>process.exit(0),10)'], {input: 'x'.repeat(60_000), timeoutMs: 2_000}); assert.equal(result.stdout, '') })
test('child stderr is retained only as protected, redacted diagnostics', async () => { const secret = `token=${'s'.repeat(48)}`; await assert.rejects(() => runBounded(process.execPath, ['-e', `process.stderr.write(${JSON.stringify(secret)});process.exit(7)`]), (error: unknown) => error instanceof CommandExecutionError && error.commandCode === 'exit_nonzero' && !error.message.includes(secret) && !JSON.stringify(error).includes(secret) && !error.protectedDetails.includes('s'.repeat(48))) })
test('SSH transport bounds remote output and uses only its fixed helper target', async () => {
  const root = await mkdtemp(path.join(os.tmpdir(), 'dsh-ssh-')); const script = path.join(root, 'fake-ssh'); await writeFile(script, '#!/bin/sh\nprintf \'%010000d\' 1\n', {mode: 0o700}); await chmod(script, 0o700); const transport = new SshJsonTransport({binary: script, host: 'remote.example', user: 'controller', knownHosts: path.join(root, 'known-hosts'), helper: '/usr/local/libexec/dsh-remote', timeoutMs: 1000, maxOutputBytes: 1024}); await assert.rejects(() => transport.call({operation: 'inventory'}), /exceeded bound/)
})
test('TLS transport rejects non-HTTPS or mutable endpoint forms before I/O', async () => { const transport = new TlsJsonTransport({url: 'http://example.invalid/controller', caFile: '/no/ca', certFile: '/no/cert', keyFile: '/no/key'}); await assert.rejects(() => transport.call({operation: 'inventory'}), /invalid fixed TLS endpoint/) })
test('remote deploy rejects failed tests, digest mismatch, exited containers, and unhealthy containers', async () => { const request = {repo: 'https://example.invalid/repo.git', branch: 'release', sha: 'a'.repeat(40), idempotencyKey: 'deploy-request-0001'}; const service = {name: 'api', containers: ['api'], actions: ['deploy'], deploy: {hook: '/trusted', repositories: [request.repo], branches: [request.branch], runtimePolicy: {requireRunning: true, requireHealthy: true}}} as ServiceDefinition; let digest = `sha256:${'b'.repeat(64)}`; let status = 'running'; let health: string | null = 'healthy'; let result: DeployResult = {repo: request.repo, branch: request.branch, sha: request.sha, imageDigest: digest, deployedAt: new Date().toISOString(), testState: 'passed', reachable: true, branchVerified: true}; const transport: RemoteTransport = {async call(call: RemoteCall) { if (call.operation === 'deploy') return result; return [{name: 'api', image: `repo@${digest}`, imageDigest: digest, status, health, startedAt: null, resources: {cpuPercent: null, memoryBytes: null}, controlled: false}] }}; const adapter = new RemoteDockerAdapter(transport); assert.equal((await adapter.deploy(service, request)).imageDigest, digest); result = {...result, testState: 'failed'}; await assert.rejects(() => adapter.deploy(service, request), /untrusted or incomplete/); result = {...result, testState: 'passed'}; digest = `sha256:${'c'.repeat(64)}`; await assert.rejects(() => adapter.deploy(service, request), /digest verification/); digest = result.imageDigest; status = 'exited'; await assert.rejects(() => adapter.deploy(service, request), /running-state verification/); status = 'running'; health = 'unhealthy'; await assert.rejects(() => adapter.deploy(service, request), /health verification/); service.deploy!.runtimePolicy = {requireRunning: false, requireHealthy: false}; assert.equal((await adapter.deploy(service, request)).imageDigest, digest) })
