import assert from 'node:assert/strict'
import {chmod, mkdtemp, readFile, realpath, symlink, writeFile} from 'node:fs/promises'
import os from 'node:os'
import path from 'node:path'
import test from 'node:test'
import type {ContainerView, ControllerConfig, DeployRequest, DeployResult, ServiceDefinition} from '@dsh-docker-services/shared'
import {assertConfig} from '@dsh-docker-services/shared'
import {Controller} from '../src/controller.js'
import type {DockerAdapter} from '../src/docker.js'
import {SafeError} from '../src/security.js'

class FakeDocker implements DockerAdapter {
  calls: string[] = []; deployments = 0; logText = 'safe log'; deployResultOverride?: Partial<DeployResult>
  async inventory(): Promise<ContainerView[]> { return [{name: 'api', image: 'example/api', imageDigest: `sha256:${'a'.repeat(64)}`, status: 'running', health: 'healthy', startedAt: 'now', resources: {cpuPercent: 1, memoryBytes: 2}, controlled: false}, {name: 'unmanaged', image: 'elsewhere', imageDigest: null, status: 'exited', health: null, startedAt: null, resources: {cpuPercent: null, memoryBytes: null}, controlled: false}] }
  async action(_service: ServiceDefinition, action: 'start' | 'stop' | 'restart'): Promise<void> { this.calls.push(action) }
  async logs(): Promise<string> { return this.logText }
  async deploy(_service: ServiceDefinition, request: DeployRequest): Promise<DeployResult> { this.deployments += 1; return {repo: request.repo, branch: request.branch, sha: request.sha, imageDigest: `sha256:${'b'.repeat(64)}`, deployedAt: new Date().toISOString(), testState: 'passed', reachable: true, branchVerified: true, ...this.deployResultOverride} }
}
async function fixture() {
  const root = await realpath(await mkdtemp(path.join(os.tmpdir(), 'dsh-docker-services-'))); await chmod(root, 0o700); const state = path.join(root, 'state'); const secrets = path.join(root, 'secrets'); const authKey = path.join(root, 'auth.key'); const auditKey = path.join(root, 'audit.key'); await writeFile(authKey, 'a'.repeat(32), {mode: 0o600}); await writeFile(auditKey, 'b'.repeat(32), {mode: 0o600})
  const config: ControllerConfig = {schemaVersion: 1, instance: 'example-host', docker: {kind: 'local', binary: '/usr/bin/docker', host: 'unix:///var/run/docker.sock'}, auth: {kind: 'hmac-proxy', keyFile: authKey, issuer: 'local-proxy', audience: 'docker-controller'}, audit: {checkpointFile: path.join(root, 'checkpoint', 'audit.json'), checkpointKeyFile: auditKey}, socketPath: path.join(root, 'controller.sock'), stateDir: state, secretRoot: secrets, roles: [{name: 'viewer', capabilities: ['services:read']}, {name: 'operator', capabilities: ['services:read', 'services:operate', 'deploy:execute', 'parameters:write', 'secrets:status', 'secrets:write', 'secrets:test', 'audit:read']}], services: [{name: 'api', containers: ['api'], url: 'https://api.internal.example', actions: ['inventory', 'logs', 'start', 'restart', 'deploy', 'parameters:write', 'secret:status', 'secret:set', 'secret:rotate'], parameters: [{key: 'MODE', label: 'Mode', type: 'enum', enum: ['safe', 'fast']}], deploy: {hook: '/usr/local/lib/dsh-deploy-api', repositories: ['https://example.invalid/org/api.git'], branches: ['release'], leaseMs: 5_000}, secrets: [{id: 'api-token', label: 'API token', target: path.join(secrets, 'api-token'), minLength: 8}]}]}
  const docker = new FakeDocker(); const controller = await Controller.create(config, docker); const viewer = {actor: 'viewer', role: 'viewer', capabilities: ['services:read'] as const}; const operator = {actor: 'operator', role: 'operator', capabilities: config.roles[1]!.capabilities
  }; return {root, state, secrets, config, controller, docker, viewer, operator}
}
test('inventory reports managed/unmanaged status, resources and authoritative deployment metadata', async () => { const {controller, viewer} = await fixture(); const value = await controller.inventory(viewer); assert.equal(value.services[0]?.deployment, null); assert.equal(value.services[0]?.containers[0]?.resources.memoryBytes, 2); assert.equal(value.services[0]?.containers[0]?.controlled, true); assert.equal(value.unmanaged[0]?.name, 'unmanaged') })
test('RBAC and action allowlists deny before Docker is reached with typed errors', async () => { const {controller, viewer, docker} = await fixture(); await assert.rejects(() => controller.action(viewer, 'api', 'start'), (error: unknown) => error instanceof SafeError && error.status === 403); assert.deepEqual(docker.calls, []); await assert.rejects(() => controller.action({...viewer, capabilities: ['services:read', 'services:operate']}, 'api', 'stop'), (error: unknown) => error instanceof SafeError && error.code === 'forbidden') })
test('deploy accepts only exact input, persists authoritative hook metadata, and is idempotent', async () => { const {controller, operator, docker} = await fixture(); const request = {repo: 'https://example.invalid/org/api.git', branch: 'release', sha: 'a'.repeat(40), idempotencyKey: 'deploy-request-0001'}; await assert.rejects(() => controller.deploy(operator, 'api', {...request, imageDigest: `sha256:${'c'.repeat(64)}`}), (error: unknown) => error instanceof SafeError && error.code === 'bad_request'); const first = await controller.deploy(operator, 'api', request); const second = await controller.deploy(operator, 'api', request); assert.equal(first.imageDigest, `sha256:${'b'.repeat(64)}`); assert.deepEqual(second, first); assert.equal(docker.deployments, 1); await assert.rejects(() => controller.deploy(operator, 'api', {...request, sha: 'd'.repeat(40)}), (error: unknown) => error instanceof SafeError && error.status === 409) })
test('write-only secrets never enter responses/audit and reject symlink path components', async () => { const {controller, operator, root, secrets, config} = await fixture(); const value = 'password=never-return-this-value'; const result = await controller.secret(operator, 'api', 'api-token', 'set', value); assert.equal(result.configured, true); assert.equal(JSON.stringify(result).includes(value), false); assert.equal(await readFile(path.join(secrets, 'api-token'), 'utf8'), value); const audit = await readFile(path.join(root, 'state', 'audit', 'events.jsonl'), 'utf8'); assert.equal(audit.includes(value), false); const outside = path.join(root, 'outside'); await symlink(outside, path.join(secrets, 'linked')); config.services[0]!.secrets![0]!.target = path.join(secrets, 'linked', 'token'); await assert.rejects(() => controller.secret(operator, 'api', 'api-token', 'set', 'valid-secret-value'), (error: unknown) => error instanceof SafeError && error.code === 'bad_request') })
test('parameters reject extra keys, multiline values, invalid enums and oversized input', async () => { const {controller, operator} = await fixture(); await assert.rejects(() => controller.parameters(operator, 'api', {UNKNOWN: 'x'}), (error: unknown) => error instanceof SafeError); await assert.rejects(() => controller.parameters(operator, 'api', {MODE: 'safe\nBAD=1'}), (error: unknown) => error instanceof SafeError); await assert.rejects(() => controller.parameters(operator, 'api', {MODE: 'unsafe'}), (error: unknown) => error instanceof SafeError); assert.deepEqual(await controller.parameters(operator, 'api', {MODE: 'safe'}), {saved: ['MODE']}) })
test('service logs are bounded by the adapter and redacted before return', async () => { const {controller, viewer, docker} = await fixture(); docker.logText = 'authorization: Bearer-super-sensitive-value'; const value = await controller.logs(viewer, 'api', Number.NaN); assert.equal(value.logs.includes('super-sensitive-value'), false); assert.match(value.logs, /REDACTED/) })
test('configuration rejects relative binaries, unsafe socket modes, unbounded adapters and secret escapes', async () => { const {config} = await fixture(); assert.throws(() => assertConfig({...config, docker: {...config.docker, binary: 'docker'}}), /absolute/); assert.throws(() => assertConfig({...config, socketMode: 0o666}), /socket mode/); assert.throws(() => assertConfig({...config, docker: {kind: 'ssh', binary: '/usr/bin/docker', host: 'unix:///var/run/docker.sock', ssh: {binary: '/usr/bin/ssh', host: 'host', user: 'user', knownHosts: '/etc/known', helper: '/helper', maxOutputBytes: 100_000_000}}}), /SSH adapter/); const services = structuredClone(config.services); services[0]!.secrets![0]!.target = '/tmp/escaped'; assert.throws(() => assertConfig({...config, services}), /invalid secret/) })
export {fixture}
