import assert from 'node:assert/strict'
import { mkdtemp, readFile } from 'node:fs/promises'
import os from 'node:os'
import path from 'node:path'
import test from 'node:test'
import type { ContainerView, ControllerConfig, DeployRequest, ServiceDefinition } from '@dsh-docker-services/shared'
import { Controller, ControllerError } from '../src/controller.js'
import type { DockerAdapter } from '../src/docker.js'

class FakeDocker implements DockerAdapter {
  calls: string[] = []; deployed: DeployRequest | undefined
  async inventory(): Promise<ContainerView[]> { return [{name: 'api', image: 'example/api', imageDigest: 'sha256:' + 'a'.repeat(64), status: 'running', health: 'healthy', startedAt: 'now', resources: {cpuPercent: 1, memoryBytes: 2}, controlled: false}, {name: 'unmanaged', image: 'elsewhere', imageDigest: null, status: 'exited', health: null, startedAt: null, resources: {cpuPercent: null, memoryBytes: null}, controlled: false}] }
  async action(_service: ServiceDefinition, action: 'start' | 'stop' | 'restart'): Promise<void> { this.calls.push(action) }
  async logs(): Promise<string> { return 'safe log' }
  async deploy(_service: ServiceDefinition, request: DeployRequest): Promise<void> { this.deployed = request }
}
async function fixture() { const root = await mkdtemp(path.join(os.tmpdir(), 'dsh-docker-services-')); const config: ControllerConfig = {schemaVersion: 1, instance: 'example-host', docker: {kind: 'local'}, stateDir: path.join(root, 'state'), secretRoot: path.join(root, 'secrets'), roles: [{name: 'viewer', capabilities: ['services:read']}, {name: 'operator', capabilities: ['services:read', 'services:operate', 'deploy:execute', 'parameters:write', 'secrets:write', 'secrets:test']}], services: [{name: 'api', containers: ['api'], url: 'https://api.internal.example', actions: ['inventory', 'logs', 'start', 'restart', 'deploy', 'parameters:write', 'secret:status', 'secret:set', 'secret:rotate'], parameters: [{key: 'MODE', label: 'Mode', type: 'enum', enum: ['safe', 'fast']}], deploy: {hook: '/usr/local/lib/dsh-deploy-api', repositories: ['https://example.invalid/org/api.git'], branches: ['release'], requireImageDigest: true}, secrets: [{id: 'api-token', label: 'API token', target: path.join(root, 'secrets', 'api-token'), minLength: 8}]}]}; const docker = new FakeDocker(); return {root, controller: new Controller(config, docker), docker, viewer: {actor: 'viewer', capabilities: ['services:read'] as const}, operator: {actor: 'operator', capabilities: ['services:read', 'services:operate', 'deploy:execute', 'parameters:write', 'secrets:write', 'secrets:test'] as const}} }
test('inventory controls visibility and excludes unmanaged from service operations', async () => { const {controller, viewer} = await fixture(); const value = await controller.inventory(viewer); assert.equal(value.services[0]?.deployment.url, 'https://api.internal.example'); assert.equal(value.services[0]?.containers[0]?.controlled, true); assert.equal(value.unmanaged[0]?.name, 'unmanaged') })
test('RBAC and service action allowlists deny before Docker is reached', async () => { const {controller, viewer, docker} = await fixture(); await assert.rejects(() => controller.action(viewer, 'api', 'start'), (error: unknown) => error instanceof ControllerError && error.status === 403); assert.deepEqual(docker.calls, []); await assert.rejects(() => controller.action({...viewer, capabilities: ['services:read', 'services:operate']}, 'api', 'stop'), /service action is not allowlisted/) })
test('deploy requires an allowlisted exact revision and writes no arbitrary shell input', async () => { const {controller, operator, docker} = await fixture(); await assert.rejects(() => controller.deploy(operator, 'api', {repo: 'https://elsewhere.invalid/repo', branch: 'release', sha: 'a'.repeat(40), imageDigest: 'sha256:' + 'b'.repeat(64)}), /exact-revision policy/); await controller.deploy(operator, 'api', {repo: 'https://example.invalid/org/api.git', branch: 'release', sha: 'a'.repeat(40), imageDigest: 'sha256:' + 'b'.repeat(64), testState: 'passed'}); assert.equal(docker.deployed?.sha, 'a'.repeat(40)) })
test('secrets are write-only, atomically persisted, and absent from audit records', async () => { const {controller, operator, root} = await fixture(); const value = 'never-return-this-value'; const result = await controller.secret(operator, 'api', 'api-token', 'set', value); assert.equal(result.configured, true); assert.equal(JSON.stringify(result).includes(value), false); assert.equal(await readFile(path.join(root, 'secrets', 'api-token'), 'utf8'), value); const audit = await readFile(path.join(root, 'state', 'audit', 'events.jsonl'), 'utf8'); assert.equal(audit.includes(value), false); assert.match(audit, /"hash":"[a-f0-9]{64}"/) })
test('parameter values are constrained by the non-secret schema', async () => { const {controller, operator} = await fixture(); await assert.rejects(() => controller.parameters(operator, 'api', {MODE: 'unsafe'}), /not an allowed value/); assert.deepEqual(await controller.parameters(operator, 'api', {MODE: 'safe'}), {saved: ['MODE']}) })
