import assert from 'node:assert/strict'
import {chmod, lstat, mkdir, mkdtemp, readFile, realpath, symlink, truncate, writeFile} from 'node:fs/promises'
import http from 'node:http'
import os from 'node:os'
import path from 'node:path'
import test from 'node:test'
import type {ControllerConfig} from '@dsh-docker-services/shared'
import {AuditLog, KeyedFileCheckpointSink, LeaseLockManager} from '../src/state.js'
import {ConflictError, ensureOwnedRoot, HmacProxyAuthenticator, ProtectedLogger, signProxyAssertion} from '../src/security.js'
import {createServer} from '../src/server.js'
import type {Controller} from '../src/controller.js'

async function secureRoot(): Promise<string> { const root = await realpath(await mkdtemp(path.join(os.tmpdir(), 'dsh-security-'))); await chmod(root, 0o700); return root }
test('signed proxy authentication rejects caller role headers, tampering, expiry, and replay', async () => {
  const root = await secureRoot(); const key = Buffer.from('k'.repeat(32)); const keyFile = path.join(root, 'auth.key'); await writeFile(keyFile, key, {mode: 0o600}); const config = {kind: 'hmac-proxy' as const, keyFile, issuer: 'trusted-proxy', audience: 'controller', maxClockSkewSeconds: 5}; const auth = await HmacProxyAuthenticator.create(config, [{name: 'viewer', capabilities: ['services:read']}]); const now = Math.floor(Date.now() / 1000); const claims = {iss: 'trusted-proxy', aud: 'controller', sub: 'alice', role: 'viewer', iat: now, exp: now + 30, nonce: 'nonce-000000000001'}; const signed = signProxyAssertion(key, claims)
  assert.equal(auth.authenticate({'x-dsh-proxy-assertion': signed}).actor, 'alice'); assert.throws(() => auth.authenticate({'x-dsh-proxy-assertion': signed}), (error: unknown) => error instanceof Error && /replayed/.test(error.message)); assert.throws(() => auth.authenticate({'x-dsh-proxy-assertion': `${signed}x`}), /signature/); assert.throws(() => auth.authenticate({'x-dsh-proxy-assertion': signProxyAssertion(key, {...claims, nonce: 'nonce-000000000002'}), 'x-dsh-role': 'operator'}), /forbidden/); assert.throws(() => auth.authenticate({'x-dsh-proxy-assertion': signProxyAssertion(key, {...claims, nonce: 'nonce-000000000003', iat: now - 100, exp: now - 50})}), /claims/)
})
test('audit appends are serialized, fsynced/checkpointed, and truncation is unhealthy', async () => {
  const root = await secureRoot(); const state = path.join(root, 'state'); const checkpointDir = path.join(root, 'offhost'); const keyFile = path.join(root, 'audit.key'); await writeFile(keyFile, 'z'.repeat(32), {mode: 0o600}); const sink = await KeyedFileCheckpointSink.create(path.join(checkpointDir, 'checkpoint.json'), keyFile); const audit = await AuditLog.create(state, sink)
  await Promise.all(Array.from({length: 40}, (_, index) => audit.append({actor: `actor-${index}`, capability: 'services:read', action: 'inventory', outcome: 'ok'}))); const entries = await audit.read(100); assert.deepEqual(entries.map(entry => entry.sequence), Array.from({length: 40}, (_, index) => index + 1)); const checkpoint = await sink.read(); assert.equal(checkpoint?.sequence, 40); const logFile = path.join(state, 'audit', 'events.jsonl'); await truncate(logFile, Math.max(0, (await readFile(logFile)).length - 20)); const reopened = await AuditLog.create(state, await KeyedFileCheckpointSink.create(path.join(checkpointDir, 'checkpoint.json'), keyFile)); assert.equal(reopened.health().healthy, false); assert.match(reopened.health().reason, /truncation|rollback/)
})
test('deployment leases return typed conflicts and expired leases are recoverable', async () => {
  const root = await secureRoot(); const manager = new LeaseLockManager(root); let release!: () => void; const held = manager.withLease('api', 'request-0000000001', 5_000, () => new Promise<void>(resolve => { release = resolve })); while (!release) await new Promise(resolve => setImmediate(resolve)); await assert.rejects(() => manager.withLease('api', 'request-0000000002', 5_000, async () => undefined), (error: unknown) => error instanceof ConflictError && error.status === 409); release(); await held
  const locks = path.join(root, 'locks'); await writeFile(path.join(locks, 'worker.lock'), JSON.stringify({token: 'old', idempotencyKey: 'request-0000000003', expiresAt: Date.now() - 1000}), {mode: 0o600}); assert.equal(await manager.withLease('worker', 'request-0000000004', 5_000, async () => 'recovered'), 'recovered')
})
test('HTTP errors are opaque while protected logs are bounded and redacted', async t => {
  const root = await secureRoot(); const logFile = path.join(root, 'errors.jsonl'); const fake = {inventory: async () => { throw new Error('password=hunter2 token=' + 'x'.repeat(100)) }} as unknown as Controller; const server = createServer(fake, {authenticate: () => ({actor: 'alice', role: 'viewer', capabilities: ['services:read']})}, new ProtectedLogger(logFile)); await new Promise<void>(resolve => server.listen(0, '127.0.0.1', resolve)); t.after(() => new Promise<void>(resolve => server.close(() => resolve()))); const address = server.address(); assert(address && typeof address === 'object'); const response = await new Promise<{status?: number; body: string}>(resolve => { http.get({host: '127.0.0.1', port: address.port, path: '/v1/services'}, res => { const chunks: Buffer[] = []; res.on('data', chunk => chunks.push(Buffer.from(chunk))); res.on('end', () => resolve({status: res.statusCode, body: Buffer.concat(chunks).toString('utf8')})) }) }); assert.equal(response.status, 500); assert.equal(response.body.includes('hunter2'), false); assert.match(response.body, /"code":"internal"/); const log = await readFile(logFile, 'utf8'); assert.equal(log.includes('hunter2'), false); assert.match(log, /\[REDACTED\]/)
})
test('writable roots reject symlink path components', async () => { const root = await secureRoot(); const target = path.join(root, 'real'); await mkdir(target, {mode: 0o700}); const linked = path.join(root, 'linked'); await symlink(target, linked); await assert.rejects(() => ensureOwnedRoot(path.join(linked, 'state')), /symlink path component rejected/) })
test('protected error logs redact each entry and rotate at a configured bound', async () => { const root = await secureRoot(); const file = path.join(root, 'errors.jsonl'); const logger = new ProtectedLogger(file, 80); await logger.log('request-one', new Error(`token=${'x'.repeat(300)}`)); await logger.log('request-two', new Error(`password=${'y'.repeat(300)}`)); assert((await lstat(file)).size < 500); assert((await lstat(`${file}.1`)).isFile()); assert.equal((await readFile(file, 'utf8')).includes('y'.repeat(40)), false) })
