import assert from 'node:assert/strict'
import {createHmac} from 'node:crypto'
import {chmod, lstat, mkdir, mkdtemp, readFile, realpath, symlink, truncate, writeFile} from 'node:fs/promises'
import {execFile} from 'node:child_process'
import {promisify} from 'node:util'
import http from 'node:http'
import os from 'node:os'
import path from 'node:path'
import test from 'node:test'
import {proxyProtocolVersion, requestCanonical, selectedHeaders, sha256Hex, signMac, type ControllerConfig, type RequestBinding} from '@dsh-docker-services/shared'
import {AuditLog, KeyedFileCheckpointSink, LeaseLockManager} from '../src/state.js'
import {ConflictError, ensureOwnedRoot, HmacProxyAuthenticator, ProtectedLogger, signControllerProof, signProxyAssertion} from '../src/security.js'
import {createServer, type RequestAuthenticator} from '../src/server.js'
import {CommandExecutionError, runBounded} from '../src/docker.js'
import type {Controller} from '../src/controller.js'

async function secureRoot(): Promise<string> { const root = await realpath(await mkdtemp(path.join(os.tmpdir(), 'dsh-security-'))); await chmod(root, 0o700); return root }
const testHeaders = {'x-dsh-proxy-assertion':'test-assertion','x-dsh-protocol-version':'1','x-dsh-request-id':'test-request-id-00001','x-dsh-request-nonce':'test-request-nonce-0001','x-dsh-request-mac':'test-mac','content-length':'0'}
function testAuthenticator(): RequestAuthenticator { return {authenticate: () => ({actor:'alice',role:'viewer',capabilities:['services:read']}), async authenticateRequest(headers, method, target, rawBody) { const binding: RequestBinding = {protocolVersion:proxyProtocolVersion,requestId:String(headers['x-dsh-request-id']),nonce:String(headers['x-dsh-request-nonce']),actor:'alice',role:'viewer',method,target,headers:selectedHeaders({'content-type':typeof headers['content-type']==='string'?headers['content-type']:undefined,'content-length':typeof headers['content-length']==='string'?headers['content-length']:undefined},['content-type','content-length']),bodyDigest:sha256Hex(rawBody),bodyLength:rawBody.length};return {identity:{actor:'alice',role:'viewer',capabilities:['services:read']},binding,digest:sha256Hex(requestCanonical(binding))} },signResponse: (_request,status) => ({binding:{outcome:status>=200&&status<300?'ok':'error'},mac:'test-mac'})} }
test('signed proxy authentication rejects caller role headers, tampering, expiry, and replay', async () => {
  const root = await secureRoot(); const key = Buffer.from('k'.repeat(32)); const keyFile = path.join(root, 'auth.key'); await writeFile(keyFile, key, {mode: 0o600}); const config = {kind: 'hmac-proxy' as const, keyFile, issuer: 'trusted-proxy', audience: 'controller', maxClockSkewSeconds: 5}; const replayRoot = path.join(root, 'replay'); const roles: ControllerConfig['roles'] = [{name: 'viewer', capabilities: ['services:read']}]; const auth = await HmacProxyAuthenticator.create(config, roles, replayRoot); const now = Math.floor(Date.now() / 1000); const claims = {iss: 'trusted-proxy', aud: 'controller', sub: 'alice', role: 'viewer', iat: now, exp: now + 30, nonce: 'nonce-000000000001'}; const signed = signProxyAssertion(key, claims)
  assert.equal((await auth.authenticate({'x-dsh-proxy-assertion': signed})).actor, 'alice'); await assert.rejects(() => auth.authenticate({'x-dsh-proxy-assertion': signed}), /replayed/); await assert.rejects(() => auth.authenticate({'x-dsh-proxy-assertion': `${signed}x`}), /signature/); await assert.rejects(() => auth.authenticate({'x-dsh-proxy-assertion': signProxyAssertion(key, {...claims, nonce: 'nonce-000000000002'}), 'x-dsh-role': 'operator'}), /forbidden/); await assert.rejects(() => auth.authenticate({'x-dsh-proxy-assertion': signProxyAssertion(key, {...claims, nonce: 'nonce-000000000003', iat: now - 100, exp: now - 50})}), /claims/)
  const restarted = await HmacProxyAuthenticator.create(config, roles, replayRoot); await assert.rejects(() => restarted.authenticate({'x-dsh-proxy-assertion': signed}), /replayed/)
  for (const [nonce, iat, exp] of [['nonce-string-time-01', String(now), now + 30], ['nonce-string-time-02', now, String(now + 30)], ['nonce-nan-time-0001', Number.NaN, now + 30], ['nonce-long-life-0001', now, now + 301]] as const) await assert.rejects(() => restarted.authenticate({'x-dsh-proxy-assertion': signProxyAssertion(key, {...claims, nonce, iat, exp} as never)}), /claims/)
})
test('request MAC binds the exact method, normalized target, selected headers, body, and full replay identity before parsing', async () => {
  const root=await secureRoot();const key=Buffer.from('q'.repeat(32));const keyFile=path.join(root,'auth.key');await writeFile(keyFile,key,{mode:0o600});const config={kind:'hmac-proxy' as const,keyFile,issuer:'proxy',audience:'controller'};const roles:ControllerConfig['roles']=[{name:'viewer',capabilities:['services:read']}];const now=Math.floor(Date.now()/1000)
  const build=(suffix:string, body=Buffer.from('{"value":1}')) => { const claims={iss:'proxy',aud:'controller',sub:'alice',role:'viewer',iat:now,exp:now+30,nonce:`assertion-nonce-${suffix}`};const binding:RequestBinding={protocolVersion:proxyProtocolVersion,requestId:`request-id-${suffix}`,nonce:`request-nonce-${suffix}`,actor:'alice',role:'viewer',method:'POST',target:'/v1/services/api/parameters?mode=safe',headers:selectedHeaders({'content-type':'application/json','content-length':String(body.length)},['content-type','content-length']),bodyDigest:sha256Hex(body),bodyLength:body.length};return {body,binding,headers:{'x-dsh-proxy-assertion':signProxyAssertion(key,claims),'x-dsh-protocol-version':'1','x-dsh-request-id':binding.requestId,'x-dsh-request-nonce':binding.nonce,'x-dsh-request-mac':signMac(key,'request',requestCanonical(binding)),'content-type':'application/json','content-length':String(body.length)}} }
  const good=build('0000000000000001');const auth=await HmacProxyAuthenticator.create(config,roles,path.join(root,'replay'));assert.equal((await auth.authenticateRequest(good.headers,'POST',good.binding.target,good.body)).identity.actor,'alice');await assert.rejects(()=>auth.authenticateRequest(good.headers,'POST',good.binding.target,good.body),/replayed/)
  const mutations:Array<[string,(value:ReturnType<typeof build>)=>void]>=[['method',value=>{value.binding.method='GET'}],['path',value=>{value.binding.target='/v1/services/other'}],['query',value=>{value.binding.target='/v1/services/api/parameters?mode=other'}],['header',value=>{value.headers['content-type']='text/plain'}],['body',value=>{value.body=Buffer.from('{"value":2}')}],['length',value=>{value.headers['content-length']='1'}],['version',value=>{value.headers['x-dsh-protocol-version']='2'}],['mac',value=>{value.headers['x-dsh-request-mac']='malformed'}]]
  for (let index=0;index<mutations.length;index+=1) { const [label,mutate]=mutations[index]!;const value=build(`${String(index+2).padStart(16,'0')}`);mutate(value);const fresh=await HmacProxyAuthenticator.create(config,roles,path.join(root,`replay-${label}`));await assert.rejects(()=>fresh.authenticateRequest(value.headers,value.binding.method,value.binding.target,value.body),/binding|MAC/) }
})
test('authentication rejects short HMAC keys without exposing key material', async () => { const root = await secureRoot(); const keyFile = path.join(root, 'short.key'); const secret = 'short-secret'; await writeFile(keyFile, secret, {mode: 0o600}); await assert.rejects(() => HmacProxyAuthenticator.create({kind: 'hmac-proxy', keyFile, issuer: 'proxy', audience: 'host'}, [], path.join(root, 'replay')), (error: unknown) => error instanceof Error && !error.message.includes(secret) && /32 bytes/.test(error.message)) })
test('a valid v1 replay file migrates safely because old-domain assertions cannot validate', async () => { const root=await secureRoot();const key=Buffer.from('m'.repeat(32));const keyFile=path.join(root,'auth.key');await writeFile(keyFile,key,{mode:0o600});const replay=path.join(root,'replay');await mkdir(replay,{mode:0o700});await writeFile(path.join(replay,'nonces.json'),JSON.stringify({version:1,nonces:{'legacy-nonce-0000001':Math.floor(Date.now()/1000)+30}}),{mode:0o600});const auth=await HmacProxyAuthenticator.create({kind:'hmac-proxy',keyFile,issuer:'proxy',audience:'controller'},[{name:'viewer',capabilities:['services:read']}],replay);const now=Math.floor(Date.now()/1000);const claims={iss:'proxy',aud:'controller',sub:'alice',role:'viewer',iat:now,exp:now+30,nonce:'new-assertion-nonce-001'};assert.equal((await auth.authenticate({'x-dsh-proxy-assertion':signProxyAssertion(key,claims)})).actor,'alice');assert.match(await readFile(path.join(replay,'nonces.json'),'utf8'),/"version":2/) })
test('controller endpoint proof is domain-separated and key-authenticated', async () => { const root=await secureRoot();const key=Buffer.from('p'.repeat(32));const keyFile=path.join(root,'proof.key');await writeFile(keyFile,key,{mode:0o600});const auth=await HmacProxyAuthenticator.create({kind:'hmac-proxy',keyFile,issuer:'proxy',audience:'host'},[],path.join(root,'replay'));const challenge='challenge-000000000000000000000000';assert.equal(auth.proveController(challenge),signControllerProof(key,challenge));assert.notEqual(auth.proveController(challenge),createHmac('sha256',key).update(challenge).digest('base64url')) })
test('audit appends are serialized, fsynced/checkpointed, and truncation is unhealthy', async () => {
  const root = await secureRoot(); const state = path.join(root, 'state'); const checkpointDir = path.join(root, 'offhost'); const keyFile = path.join(root, 'audit.key'); await writeFile(keyFile, 'z'.repeat(32), {mode: 0o600}); const sink = await KeyedFileCheckpointSink.create(path.join(checkpointDir, 'checkpoint.json'), keyFile); const audit = await AuditLog.create(state, sink)
  await Promise.all(Array.from({length: 40}, (_, index) => audit.append({actor: `actor-${index}`, capability: 'services:read', action: 'inventory', outcome: 'ok'}))); const entries = await audit.read(100); assert.deepEqual(entries.map(entry => entry.sequence), Array.from({length: 40}, (_, index) => index + 1)); const checkpoint = await sink.read(); assert.equal(checkpoint?.sequence, 40); const logFile = path.join(state, 'audit', 'events.jsonl'); await truncate(logFile, Math.max(0, (await readFile(logFile)).length - 20)); const reopened = await AuditLog.create(state, await KeyedFileCheckpointSink.create(path.join(checkpointDir, 'checkpoint.json'), keyFile)); assert.equal(reopened.health().healthy, false); assert.match(reopened.health().reason, /truncation|rollback/)
})
test('audit appends remain one valid chain across two OS processes', async () => {
  const root = await secureRoot(); const state = path.join(root, 'state'); const checkpoint = path.join(root, 'offhost', 'checkpoint.json'); const keyFile = path.join(root, 'audit.key'); await writeFile(keyFile, 'q'.repeat(32), {mode: 0o600}); const helper = new URL('./helpers/audit-writer.js', import.meta.url); const run = promisify(execFile)
  await Promise.all([run(process.execPath, [helper.pathname, state, checkpoint, keyFile, 'left', '25']), run(process.execPath, [helper.pathname, state, checkpoint, keyFile, 'right', '25'])])
  const audit = await AuditLog.create(state, await KeyedFileCheckpointSink.create(checkpoint, keyFile)); const entries = await audit.read(100); assert.equal(entries.length, 50); assert.deepEqual(entries.map(entry => entry.sequence), Array.from({length: 50}, (_, index) => index + 1)); assert.equal(audit.health().healthy, true)
})
test('deployment leases return typed conflicts and expired leases are recoverable', async () => {
  const root = await secureRoot(); const manager = new LeaseLockManager(root); let release!: () => void; const held = manager.withLease('api', 'request-0000000001', 5_000, () => new Promise<void>(resolve => { release = resolve })); while (!release) await new Promise(resolve => setImmediate(resolve)); await assert.rejects(() => manager.withLease('api', 'request-0000000002', 5_000, async () => undefined), (error: unknown) => error instanceof ConflictError && error.status === 409); release(); await held
  const locks = path.join(root, 'locks'); await writeFile(path.join(locks, 'worker.lock'), JSON.stringify({version: 1, token: '00000000-0000-4000-8000-000000000000', ownerPid: process.pid, purpose: 'worker', expiresAt: Date.now() - 1000}), {mode: 0o600}); assert.equal(await manager.withLease('worker', 'request-0000000004', 5_000, async () => 'recovered'), 'recovered')
})
test('active deployment leases renew and cannot be stolen after their initial expiry', async () => { const root = await secureRoot(); const manager = new LeaseLockManager(root); let release!: () => void; const held = manager.withLease('api', 'request-renew-0001', 1_000, () => new Promise<void>(resolve => { release = resolve })); while (!release) await new Promise(resolve => setImmediate(resolve)); await new Promise(resolve => setTimeout(resolve, 1_200)); await assert.rejects(() => manager.withLease('api', 'request-renew-0002', 1_000, async () => undefined), (error: unknown) => error instanceof ConflictError); release(); await held })
test('lock integrity failures cannot be mistaken for stale leases', async () => { const root = await secureRoot(); const manager = new LeaseLockManager(root); await mkdir(path.join(root, 'locks'), {mode: 0o700}); const lock = path.join(root, 'locks', 'api.lock'); await writeFile(lock, JSON.stringify({expiresAt: 0}), {mode: 0o644}); await assert.rejects(() => manager.withLease('api', 'request-0000000001', 5_000, async () => undefined), (error: unknown) => error instanceof ConflictError && /integrity/.test(error.message)); assert.equal((await lstat(lock)).mode & 0o777, 0o644) })
test('HTTP errors are opaque while protected logs are bounded and redacted', async t => {
  const root = await secureRoot(); const logFile = path.join(root, 'errors.jsonl'); const fake = {inventory: async () => { throw new Error('password=hunter2 token=' + 'x'.repeat(100)) }} as unknown as Controller; const server = createServer(fake, testAuthenticator(), new ProtectedLogger(logFile)); await new Promise<void>(resolve => server.listen(0, '127.0.0.1', resolve)); t.after(() => new Promise<void>(resolve => server.close(() => resolve()))); const address = server.address(); assert(address && typeof address === 'object'); const response = await new Promise<{status?: number; body: string}>(resolve => { http.get({host: '127.0.0.1', port: address.port, path: '/v1/services', headers:testHeaders}, res => { const chunks: Buffer[] = []; res.on('data', chunk => chunks.push(Buffer.from(chunk))); res.on('end', () => resolve({status: res.statusCode, body: Buffer.concat(chunks).toString('utf8')})) }) }); assert.equal(response.status, 500); assert.equal(response.body.includes('hunter2'), false); assert.match(response.body, /"code":"internal"/); const log = await readFile(logFile, 'utf8'); assert.equal(log.includes('hunter2'), false); assert.match(log, /\[REDACTED\]/)
})
test('exact short child output is absent from every error serialization and protected/public log', async t => {
  const secret = 'violet-7'; let commandError: CommandExecutionError | undefined
  try { await runBounded(process.execPath, ['-e', `process.stdout.write(${JSON.stringify(secret)});process.stderr.write(${JSON.stringify(secret)});setTimeout(()=>process.exit(7),10)`], {operation: 'deploy-hook'}) } catch (error) { if (error instanceof CommandExecutionError) commandError = error; else throw error }
  assert(commandError); const serialized = [commandError.message, String(commandError), commandError.stack ?? '', JSON.stringify(commandError), JSON.stringify(commandError.protectedDetails)]
  for (const value of serialized) assert.equal(value.includes(secret), false)
  assert.deepEqual({...commandError.protectedDetails, correlationId: '[uuid]'}, {correlationId: '[uuid]', operation: 'deploy-hook', classification: 'nonzero_exit', exitCode: 7, signal: null, stdoutBytes: 8, stderrBytes: 8}); assert.match(commandError.protectedDetails.correlationId, /^[0-9a-f-]{36}$/i)
  const root = await secureRoot(); const logFile = path.join(root, 'errors.jsonl'); const fake = {inventory: async () => { throw commandError }} as unknown as Controller; const server = createServer(fake, testAuthenticator(), new ProtectedLogger(logFile)); await new Promise<void>(resolve => server.listen(0, '127.0.0.1', resolve)); t.after(() => new Promise<void>(resolve => server.close(() => resolve()))); const address = server.address(); assert(address && typeof address === 'object'); const response = await new Promise<string>(resolve => { http.get({host: '127.0.0.1', port: address.port, path: '/v1/services', headers:testHeaders}, res => { const chunks: Buffer[] = []; res.on('data', chunk => chunks.push(Buffer.from(chunk))); res.on('end', () => resolve(Buffer.concat(chunks).toString('utf8'))) }) }); const log = await readFile(logFile, 'utf8'); assert.equal(response.includes(secret), false); assert.equal(log.includes(secret), false); assert.match(response, /"code":"unavailable"/); assert.match(log, /nonzero_exit/); assert.match(log, new RegExp(commandError.protectedDetails.correlationId))
})
test('writable roots require exact 0700 permissions', async () => { const root = await secureRoot(); const accepted = path.join(root, 'accepted'); await mkdir(accepted, {mode: 0o700}); await chmod(accepted, 0o700); await ensureOwnedRoot(accepted); for (const mode of [0o750, 0o710, 0o701, 0o770, 0o000, 0o1700, 0o2700, 0o4700, 0o5700, 0o6700, 0o7700]) { const candidate = path.join(root, mode.toString(8)); await mkdir(candidate, {mode: 0o700}); await chmod(candidate, mode); await assert.rejects(() => ensureOwnedRoot(candidate), /exact mode 0700/) } })
test('writable roots reject symlink path components', async () => { const root = await secureRoot(); const target = path.join(root, 'real'); await mkdir(target, {mode: 0o700}); const linked = path.join(root, 'linked'); await symlink(target, linked); await assert.rejects(() => ensureOwnedRoot(path.join(linked, 'state')), /symlink path component rejected/) })
test('protected error logs redact each entry and rotate at a configured bound', async () => { const root = await secureRoot(); const file = path.join(root, 'errors.jsonl'); const logger = new ProtectedLogger(file, 80); await logger.log('request-one', new Error(`token=${'x'.repeat(300)}`)); await logger.log('request-two', new Error(`password=${'y'.repeat(300)}`)); assert((await lstat(file)).size < 500); assert((await lstat(`${file}.1`)).isFile()); assert.equal((await readFile(file, 'utf8')).includes('y'.repeat(40)), false) })
test('protected logger tightens an existing 0644 file before appending', async () => { const root = await secureRoot(); const file = path.join(root, 'errors.jsonl'); await writeFile(file, 'existing\n', {mode: 0o644}); await new ProtectedLogger(file).log('request-mode', new Error('safe')); assert.equal((await lstat(file)).mode & 0o777, 0o600) })
