import {createHash} from 'node:crypto'
import {execFileSync} from 'node:child_process'
import {mkdir,readFile,readdir,rm,writeFile} from 'node:fs/promises'
import path from 'node:path'

const syft='anchore/syft:v1.30.0@sha256:bd5357d2cd087f03af748dac24df48bfbc1723080d78f75f69aca1f2d429060e'
const root=process.cwd();const artifactRoot=path.join(root,'artifacts');const output=path.join(artifactRoot,'sbom');const input=path.join(artifactRoot,'.sbom-input');const command=process.argv[2]??'verify'
const hash=async file=>createHash('sha256').update(await readFile(file)).digest('hex')
const artifacts=(await readdir(artifactRoot)).filter(file=>file.endsWith('.tgz')).sort();if(artifacts.length!==4)throw new Error(`SBOM requires four release artifacts, found ${artifacts.length}`)
if(command==='generate'){
  await rm(output,{recursive:true,force:true});await rm(input,{recursive:true,force:true});await mkdir(output,{recursive:true,mode:0o700});await mkdir(input,{recursive:true,mode:0o700})
  const user=typeof process.getuid==='function'&&typeof process.getgid==='function'?`${process.getuid()}:${process.getgid()}`:'0:0'
  try{for(const file of artifacts){const source=path.join(input,file);await mkdir(source,{recursive:true});execFileSync('tar',['-xzf',path.join(artifactRoot,file),'-C',source]);const packageManifest=JSON.parse(await readFile(path.join(source,'package','package.json'),'utf8'));const destination=`/out/${file}.cdx.json`;execFileSync('docker',['run','--rm','--network','none','--user',user,'--env','SYFT_CHECK_FOR_APP_UPDATE=false','--volume',`${root}:/src:ro`,'--volume',`${output}:/out`,syft,`dir:/src/artifacts/.sbom-input/${file}/package`,'--source-name',packageManifest.name,'--source-version',packageManifest.version,'--select-catalogers','+javascript-package-cataloger','--output',`cyclonedx-json=${destination}`],{stdio:'inherit'})}}finally{await rm(input,{recursive:true,force:true})}
  const entries=[];for(const file of artifacts)entries.push({artifact:file,artifactSha256:await hash(path.join(artifactRoot,file)),sbom:`${file}.cdx.json`,sbomSha256:await hash(path.join(output,`${file}.cdx.json`))});await writeFile(path.join(output,'manifest.json'),JSON.stringify({schemaVersion:1,generator:syft,entries},null,2)+'\n',{mode:0o600})
}else if(command!=='verify')throw new Error('usage: node scripts/sbom.mjs generate|verify')
const manifest=JSON.parse(await readFile(path.join(output,'manifest.json'),'utf8'));if(manifest.schemaVersion!==1||manifest.generator!==syft||!Array.isArray(manifest.entries)||manifest.entries.length!==4)throw new Error('invalid SBOM manifest')
for(const entry of manifest.entries){if(!artifacts.includes(entry.artifact)||entry.sbom!==`${entry.artifact}.cdx.json`||entry.artifactSha256!==await hash(path.join(artifactRoot,entry.artifact))||entry.sbomSha256!==await hash(path.join(output,entry.sbom)))throw new Error(`SBOM manifest mismatch for ${entry.artifact}`);const packageManifest=JSON.parse(execFileSync('tar',['-xOzf',path.join(artifactRoot,entry.artifact),'package/package.json'],{encoding:'utf8'}));const bom=JSON.parse(await readFile(path.join(output,entry.sbom),'utf8'));if(bom.bomFormat!=='CycloneDX'||typeof bom.specVersion!=='string'||!Array.isArray(bom.components))throw new Error(`invalid CycloneDX SBOM for ${entry.artifact}`);if(!bom.components.some(component=>component.name===packageManifest.name&&component.version===packageManifest.version))throw new Error(`SBOM lacks root package ${packageManifest.name}@${packageManifest.version}`);const toolText=JSON.stringify(bom.metadata?.tools??'');if(!toolText.includes('syft')||!toolText.includes('1.30.0'))throw new Error(`SBOM lacks pinned Syft identity for ${entry.artifact}`)}
console.log(`verified four CycloneDX release SBOMs with ${syft}`)
